### ISSUE TITLE
Broken on mobile

### ISSUE THREAD

**Issue by gb444** [Polymer/core-dropdown#10] opened 2014-11-07 11:53 UTC
Using the core demo at https://www.polymer-project.org/components/core-elements/demo.html on both a TF201 and Nexus 5 with up to date Chrome, I cannot select any of the options of the dropdowns. One of the dropdown menus works as expected but otherwise they don't appear, appear and disapear on the second click, sometimes while selecting something that isn't really displayed. Upwards dropdowns seem to be more successful.

**Comment by ssorallen** [comment] 2015-01-16 20:45
Are you referring to the core-dropdown-menu? And which of the menus seems not to work? I tested https://www.polymer-project.org/components/core-elements/demo.html#core-dropdown-menu on a Nexus 5 with latest Chrome and was able to select items in each of the `<core-dropdown-menu>` elements.

**Comment by gb444** [comment] 2015-01-20 11:01
I agree, it seems to be working. Has any of the mobile code been updated? I suppose this should be closed then.

**Comment by ssorallen** [comment] 2015-01-20 17:07
I'll close this for now since neither of us can reproduce it. Please reopen the issue if you see it happen again.

**Closed by ssorallen** 2015-01-20 17:07 UTC
